# Generated by Django 5.2.1 on 2025-05-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(max_length=5000, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
