# Generated by Django 5.2 on 2025-05-28 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userfavoritearticles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfavoritearticles',
            options={'ordering': ['-faved_at']},
        ),
    ]
